channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
#  - bioconda::snakemake-minimal =5.4.5
  - python =3.8
  - jinja2 =2.10
  - networkx =2.1
  - matplotlib =3.1.0
  - graphviz =2.38.0
  - bcftools =1.9
  - bwa =0.7.17
  - pysam =0.15.0
